name: django-cicd
on:
  push:
    branches: [develop]
jobs: 
 deploy:  
  runs-on: [aws-ec2]
  steps:
    - name: checkout the code
      uses: actions/checkout@v2
    - name: deploying the code
      run: |
        docker-compose down && docker-compose up
