name: django-cicd
on:
  push:
    branches: [develop]
jobs: 
 deploy:  
  runs-on: self-hosted
  steps:
    - name: checkout the code
      uses: actions/checkout@v2
    - name: connect to ec2
      env:
        PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        HOSTNAME: ${{ secrets.HOSTNAME }}
        USER: ubuntu
      run: |
        echo "Connecting to ec2 "
        echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
        ssh -i private_key ${USER}@${HOSTNAME} -y
        echo "connection successfull"
